export const TRADES_PAGE_SIZE = 10;

export const DEFAULT_PAIRS = [
  // ── Forex Majors ────────────────────────────────────────────
  { group: "Majors",    value: "EURUSD"  },
  { group: "Majors",    value: "GBPUSD"  },
  { group: "Majors",    value: "USDJPY"  },
  { group: "Majors",    value: "USDCHF"  },
  { group: "Majors",    value: "AUDUSD"  },
  { group: "Majors",    value: "NZDUSD"  },
  { group: "Majors",    value: "USDCAD"  },

  // ── Forex Minors (crosses — no USD) ─────────────────────────
  { group: "Minors",    value: "EURGBP"  },
  { group: "Minors",    value: "EURJPY"  },
  { group: "Minors",    value: "EURCHF"  },
  { group: "Minors",    value: "EURAUD"  },
  { group: "Minors",    value: "EURCAD"  },
  { group: "Minors",    value: "EURNZD"  },
  { group: "Minors",    value: "GBPJPY"  },
  { group: "Minors",    value: "GBPCHF"  },
  { group: "Minors",    value: "GBPAUD"  },
  { group: "Minors",    value: "GBPCAD"  },
  { group: "Minors",    value: "GBPNZD"  },
  { group: "Minors",    value: "AUDJPY"  },
  { group: "Minors",    value: "AUDCHF"  },
  { group: "Minors",    value: "AUDCAD"  },
  { group: "Minors",    value: "AUDNZD"  },
  { group: "Minors",    value: "CADJPY"  },
  { group: "Minors",    value: "CADCHF"  },
  { group: "Minors",    value: "NZDJPY"  },
  { group: "Minors",    value: "NZDCHF"  },
  { group: "Minors",    value: "NZDCAD"  },
  { group: "Minors",    value: "CHFJPY"  },

  // ── Forex Exotics ────────────────────────────────────────────
  { group: "Exotics",   value: "USDTRY"  },
  { group: "Exotics",   value: "USDZAR"  },
  { group: "Exotics",   value: "USDMXN"  },
  { group: "Exotics",   value: "USDSEK"  },
  { group: "Exotics",   value: "USDNOK"  },
  { group: "Exotics",   value: "USDDKK"  },
  { group: "Exotics",   value: "USDSGD"  },
  { group: "Exotics",   value: "USDHKD"  },
  { group: "Exotics",   value: "USDCNH"  },
  { group: "Exotics",   value: "USDTHB"  },
  { group: "Exotics",   value: "USDPLN"  },
  { group: "Exotics",   value: "USDHUF"  },
  { group: "Exotics",   value: "USDCZK"  },
  { group: "Exotics",   value: "USDINR"  },
  { group: "Exotics",   value: "USDBRL"  },
  { group: "Exotics",   value: "USDKRW"  },
  { group: "Exotics",   value: "USDNGN"  },
  { group: "Exotics",   value: "USDKES"  },
  { group: "Exotics",   value: "USDEGP"  },
  { group: "Exotics",   value: "USDGHS"  },
  { group: "Exotics",   value: "EURTRY"  },
  { group: "Exotics",   value: "EURZAR"  },
  { group: "Exotics",   value: "EURSEK"  },
  { group: "Exotics",   value: "EURNOK"  },
  { group: "Exotics",   value: "EURDKK"  },
  { group: "Exotics",   value: "EURPLN"  },
  { group: "Exotics",   value: "EURHUF"  },
  { group: "Exotics",   value: "EURCZK"  },
  { group: "Exotics",   value: "GBPTRY"  },
  { group: "Exotics",   value: "GBPZAR"  },
  { group: "Exotics",   value: "GBPSEK"  },
  { group: "Exotics",   value: "GBPNOK"  },
  { group: "Exotics",   value: "GBPSGD"  },
  { group: "Exotics",   value: "AUDSGD"  },
  { group: "Exotics",   value: "SGDJPY"  },

  // ── Metals & Commodities ─────────────────────────────────────
  { group: "Metals",    value: "XAUUSD"  },
  { group: "Metals",    value: "XAGUSD"  },
  { group: "Metals",    value: "XPTUSD"  },
  { group: "Metals",    value: "XPDUSD"  },
  { group: "Metals",    value: "XAUEUR"  },
  { group: "Metals",    value: "XAUGBP"  },
  { group: "Metals",    value: "XAUJPY"  },
  { group: "Metals",    value: "XAUAUD"  },
  { group: "Metals",    value: "XAGEUR"  },

  // ── Indices ──────────────────────────────────────────────────
  { group: "Indices",   value: "NAS100"  },
  { group: "Indices",   value: "SPX500"  },
  { group: "Indices",   value: "US30"    },
  { group: "Indices",   value: "US2000"  },
  { group: "Indices",   value: "GER40"   },
  { group: "Indices",   value: "UK100"   },
  { group: "Indices",   value: "FRA40"   },
  { group: "Indices",   value: "ESP35"   },
  { group: "Indices",   value: "JPN225"  },
  { group: "Indices",   value: "AUS200"  },
  { group: "Indices",   value: "HKG50"   },
  { group: "Indices",   value: "CHN50"   },
  { group: "Indices",   value: "STOXX50" },
  { group: "Indices",   value: "VIX"     },

  // ── Crypto ───────────────────────────────────────────────────
  { group: "Crypto",    value: "BTCUSDT" },
  { group: "Crypto",    value: "ETHUSDT" },
  { group: "Crypto",    value: "SOLUSDT" },
  { group: "Crypto",    value: "BNBUSDT" },
  { group: "Crypto",    value: "XRPUSDT" },
  { group: "Crypto",    value: "ADAUSDT" },
  { group: "Crypto",    value: "DOGEUSDT"},
  { group: "Crypto",    value: "AVAXUSDT"},
  { group: "Crypto",    value: "LINKUSDT"},
  { group: "Crypto",    value: "LTCUSDT" },
  { group: "Crypto",    value: "BTCEUR"  },
  { group: "Crypto",    value: "ETHEUR"  },

  // ── Energy ───────────────────────────────────────────────────
  { group: "Energy",    value: "USOIL"   },
  { group: "Energy",    value: "UKOIL"   },
  { group: "Energy",    value: "NGAS"    },
];

export const GROUP_ORDER = ["Majors", "Minors", "Exotics", "Metals", "Indices", "Crypto", "Energy"];